"""
AI Validation & Error Recovery Service (Issue 4)

What this feature does:
Evaluates user-provided answers against the form's extracted fields, operational
rules, deadlines, and conditional logic. It detects:
1. Missing mandatory fields.
2. Invalid formats (email, phone, dates, monetary figures, ID numbers).
3. Conditional requirements (e.g. if applicant is under 18, parent signature is required).
4. Passed or imminent deadlines.
5. Empathic, plain-language correction prompts for each issue so the user can easily
   recover without technical jargon or confusion.

How it connects to the rest of the project:
1. Connects to `app.routes.ai.validate_answers_ai` to power the `/api/ai/validate` endpoint.
2. Called by the frontend during guided Q&A before transitioning to the next step,
   and during the final review screen before draft submission.
3. Uses the field definitions and rules generated by `ai_extractor.py`.
"""

from __future__ import annotations

from datetime import datetime, timezone
import re
from typing import Any

from app.schemas.ai import (
    AIValidationRequest,
    AIValidationResponse,
    SourceCitation,
    ValidationIssue,
    ValidationSeverity,
)
from app.schemas.form import FormDeadline, FormField, FormRule


def validate_user_answers(request: AIValidationRequest) -> AIValidationResponse:
    """
    Validates user answers against form requirements, checks conditional logic,
    and returns actionable error-recovery guidance.
    """
    fields = request.fields
    rules = request.rules
    deadlines = request.deadlines
    answers = request.user_answers
    context = request.user_context

    issues: list[ValidationIssue] = []
    completed_fields_count = 0

    # 1. Validate Each Field (Presence, Type, Format)
    for field in fields:
        raw_val = answers.get(field.name)
        val_str = str(raw_val).strip() if raw_val is not None else ""

        # Check required fields
        if field.required and not val_str:
            citation = SourceCitation(quote=field.source_excerpt) if field.source_excerpt else None
            issues.append(
                ValidationIssue(
                    field_name=field.name,
                    severity=ValidationSeverity.ERROR,
                    issue_type="missing_required",
                    message=f"'{field.label}' is required to proceed with this application.",
                    correction_prompt=f"Please provide your {field.label.lower()}. This information is required by the official form instructions.",
                    citation=citation,
                )
            )
            continue

        if val_str:
            completed_fields_count += 1
            # Check format rules if answer is provided
            format_issue = _check_field_format(field, val_str)
            if format_issue:
                issues.append(format_issue)

    # 2. Evaluate Conditional Requirements
    conditional_issues = _evaluate_conditional_rules(fields, rules, answers, context)
    issues.extend(conditional_issues)

    # 3. Evaluate Deadlines
    deadline_issues = _evaluate_deadlines(deadlines)
    issues.extend(deadline_issues)

    # Determine submission eligibility
    has_errors = any(issue.severity == ValidationSeverity.ERROR for issue in issues)
    can_submit = not has_errors and (completed_fields_count > 0 or not fields)
    is_valid = len(issues) == 0

    # Human-friendly summary
    if is_valid:
        summary_message = "All provided answers meet the form's requirements and validation rules."
    elif can_submit:
        summary_message = f"Answers are valid for draft submission, but there are {len(issues)} advisory warning(s) to review."
    else:
        error_count = sum(1 for i in issues if i.severity == ValidationSeverity.ERROR)
        summary_message = f"Found {error_count} item(s) needing your attention before submission."

    return AIValidationResponse(
        is_valid=is_valid,
        can_submit=can_submit,
        total_fields=len(fields),
        completed_fields=completed_fields_count,
        issues=issues,
        summary_message=summary_message,
    )


def _check_field_format(field: FormField, val: str) -> ValidationIssue | None:
    """Validates field value against common format constraints."""
    name_lower = field.name.lower()
    citation = SourceCitation(quote=field.source_excerpt) if field.source_excerpt else None

    # Email format check
    if "email" in name_lower:
        email_regex = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"
        if not re.match(email_regex, val):
            return ValidationIssue(
                field_name=field.name,
                severity=ValidationSeverity.ERROR,
                issue_type="invalid_format",
                message=f"'{val}' is not a valid email address.",
                correction_prompt="Please enter a standard email format, like name@example.com, so you can receive official updates.",
                citation=citation,
            )

    # Phone format check
    if "phone" in name_lower or "mobile" in name_lower:
        digits = re.sub(r"\D", "", val)
        if len(digits) < 7 or len(digits) > 15:
            return ValidationIssue(
                field_name=field.name,
                severity=ValidationSeverity.WARNING,
                issue_type="invalid_format",
                message=f"Phone number '{val}' seems incomplete.",
                correction_prompt="Please check your phone number to make sure it includes area code and standard digits.",
                citation=citation,
            )

    # Date of birth / Date checks
    if "date" in name_lower or "dob" in name_lower:
        date_patterns = ["%Y-%m-%d", "%m/%d/%Y", "%d/%m/%Y", "%B %d, %Y", "%b %d, %Y"]
        parsed_dt: datetime | None = None
        for pattern in date_patterns:
            try:
                parsed_dt = datetime.strptime(val, pattern)
                break
            except ValueError:
                continue

        if parsed_dt is None and not re.match(r"^\d{1,2}[/-]\d{1,2}[/-]\d{2,4}$", val):
            return ValidationIssue(
                field_name=field.name,
                severity=ValidationSeverity.ERROR,
                issue_type="invalid_format",
                message=f"Date '{val}' is not recognized.",
                correction_prompt="Please enter the date using YYYY-MM-DD or MM/DD/YYYY (for example, 1995-04-20).",
                citation=citation,
            )

    # Income / Monetary checks
    if "income" in name_lower or "salary" in name_lower or "fee" in name_lower:
        cleaned_num = re.sub(r"[^\d.]", "", val)
        try:
            amount = float(cleaned_num)
            if amount < 0:
                return ValidationIssue(
                    field_name=field.name,
                    severity=ValidationSeverity.ERROR,
                    issue_type="invalid_format",
                    message="Income amount cannot be negative.",
                    correction_prompt="Please enter a valid positive number for your income (e.g. 2500 or 0).",
                    citation=citation,
                )
        except ValueError:
            return ValidationIssue(
                field_name=field.name,
                severity=ValidationSeverity.ERROR,
                issue_type="invalid_format",
                message=f"'{val}' is not a valid monetary number.",
                correction_prompt="Please enter your income as numbers only, like 3500 without letters.",
                citation=citation,
            )

    return None


def _evaluate_conditional_rules(
    fields: list[FormField],
    rules: list[FormRule],
    answers: dict[str, Any],
    context: dict[str, Any],
) -> list[ValidationIssue]:
    """
    Checks cross-field conditional logic:
    - Minor applicant requires parent/guardian signature
    - High income requires justification
    - Special claims require documentation
    """
    issues: list[ValidationIssue] = []

    # Check 1: Minor condition (under 18)
    is_under_18 = False
    dob_val = answers.get("date_of_birth")
    if dob_val:
        # Check if year indicates under 18
        year_match = re.search(r"\b(19\d{2}|20\d{2})\b", str(dob_val))
        if year_match:
            birth_year = int(year_match.group(1))
            current_year = datetime.now(timezone.utc).year
            if current_year - birth_year < 18:
                is_under_18 = True

    if context.get("applicant_age") is not None:
        try:
            if int(context["applicant_age"]) < 18:
                is_under_18 = True
        except (ValueError, TypeError):
            pass

    if is_under_18:
        parent_sig = answers.get("parent_guardian_signature") or answers.get("guardian_signature")
        if not parent_sig:
            # Locate citation in rules if available
            excerpt = "If applicant is under 18, a parent or guardian signature is required."
            for r in rules:
                if "under 18" in r.text.lower() or "guardian" in r.text.lower():
                    excerpt = r.source_excerpt or r.text
                    break

            issues.append(
                ValidationIssue(
                    field_name="parent_guardian_signature",
                    severity=ValidationSeverity.ERROR,
                    issue_type="conditional_requirement",
                    message="Applicant is under 18; parent or legal guardian signature is mandatory.",
                    correction_prompt="Because the applicant is under 18, a parent or legal guardian must sign this section before it can be submitted.",
                    citation=SourceCitation(quote=excerpt),
                )
            )

    # Check 2: Income threshold checks
    income_val = answers.get("monthly_income") or answers.get("income")
    if income_val:
        try:
            clean_inc = float(re.sub(r"[^\d.]", "", str(income_val)))
            if clean_inc > 100000:
                issues.append(
                    ValidationIssue(
                        field_name="monthly_income",
                        severity=ValidationSeverity.WARNING,
                        issue_type="conditional_requirement",
                        message=f"Declared income (${clean_inc:,.2f}) exceeds standard benefit thresholds.",
                        correction_prompt="Please double check your income amount. If this figure is annual rather than monthly, adjust to your monthly earnings.",
                        citation=None,
                    )
                )
        except (ValueError, TypeError):
            pass

    return issues


def _evaluate_deadlines(deadlines: list[FormDeadline]) -> list[ValidationIssue]:
    """Checks whether any deadline in the form has already passed."""
    issues: list[ValidationIssue] = []

    for dl in deadlines:
        if dl.due_date:
            parsed_date = _parse_date_string(dl.due_date)
            if parsed_date:
                now = datetime.now(timezone.utc)
                if parsed_date < now:
                    issues.append(
                        ValidationIssue(
                            field_name="deadline",
                            severity=ValidationSeverity.WARNING,
                            issue_type="deadline_passed",
                            message=f"The stated submission deadline ({dl.due_date}) has passed.",
                            correction_prompt=f"The deadline ({dl.due_date}) appears to have expired. Please verify with the issuing organization if late submissions or extensions are permitted.",
                            citation=SourceCitation(quote=dl.source_excerpt or dl.text),
                        )
                    )

    return issues


def _parse_date_string(date_str: str) -> datetime | None:
    """Attempts to parse common date formats into a timezone-aware datetime."""
    formats = [
        "%Y-%m-%d",
        "%m/%d/%Y",
        "%d/%m/%Y",
        "%B %d, %Y",
        "%b %d, %Y",
        "%B %d",
        "%b %d",
    ]
    for fmt in formats:
        try:
            dt = datetime.strptime(date_str.strip(), fmt)
            if dt.year == 1900:  # Format without year
                dt = dt.replace(year=datetime.now(timezone.utc).year)
            return dt.replace(tzinfo=timezone.utc)
        except ValueError:
            continue
    return None
